#!/usr/bin/env bash

echo "This script must be edited before using."

#*********************************
exit # Uncomment me, after editing
#*********************************

#---------------------------------------------------------------
# Edit here

GPGKEY_REALNAME="" # First name and last name
GPGKEY_EMAIL=""
ACCOUNTNAME="" # Enter whatever you want as a config name
SMTPHOST=""
FROM="" # A mail address for the FROM field for your sent mails

# End of editing
#---------------------------------------------------------------

ENCRYPTED_PASS_FILE="$HOME/.msmtp.gpg"

sudo debconf-set-selections <<< "msmtp msmtp/apparmor boolean false"
sudo apt install msmtp msmtp-mta -y

if ! gpg -k "$GPGKEY_EMAIL" > /dev/null 2>&1; then
    gpg --batch --gen-key <<EOF
%no-protection
Key-Type:1
Key-Length:2048
Subkey-Type:1
Subkey-Length:2048
Name-Real: $GPGKEY_REALNAME
Name-Email: $GPGKEY_EMAIL
Expire-Date:0
EOF
fi

echo "
# Set default values for all following \"account\" sections
defaults
port 587
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
# logfile		/var/log/msmtp.log

account $ACCOUNTNAME
host $SMTPHOST
from $FROM
auth on
user $USERNAME
passwordeval gpg --no-tty -q -d $ENCRYPTED_PASS_FILE
# If you are using pass password manager
# passwordeval \"pass email/user1\"

# Set a default account
account default : $ACCOUNTNAME
" | tee "$HOME/.msmtprc"

echo "Enter your password for your SMTP host:"
echo "Then press Enter again to go to a new line and and CTRL+D to exit."
gpg --encrypt -o "$ENCRYPTED_PASS_FILE" -r "$GPGKEY_EMAIL" -
